spring:
  application:
    name: sse-connect

  jackson:
    property-naming-strategy: SNAKE_CASE

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db
    username: admin
    password: admin

  datasource:
    url: jdbc:postgresql://localhost:5432/db
    password: admin
    username: admin
  liquibase:
    url: jdbc:postgresql://localhost:5432/db
    user: admin
    password: admin
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none

  redis:
    host: localhost
    port: 6379

resilience4j:
  circuitbreaker:
    configs:
      myCircuitBreakerConfig:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s
    instances:
      coreCircuitBreaker:
        baseConfig: myCircuitBreakerConfig
  retry:
    instances:
      coreRetry:
        max-attempts: 5
        waitDuration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - ru.abolsoft.sseconnect.core.exception.DomainException
          - java.lang.Throwable
    metrics:
      enabled: true


springdoc:
  swagger-ui:
    path: /api/swagger
    disable-swagger-default-url: true
    enabled: true
  api-docs:
    path: /api-docs
    enabled: true

app:
  core:
    superuser:
      username: admin
      password: qwerty123
management:
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true

