version: "3.9"
services:
  db:
    image: postgres:15-alpine
    expose:
      - '5432'
    command: -p 5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  cache-redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  redis_data: