version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      main_network:
        aliases:
        - prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      main_network:
        aliases:
          - grafana

  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - prometheus
    networks:
      main_network:
        aliases:
          - app

  db:
    image: postgres:15-alpine
    expose:
      - '5432'
    command: -p 5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      main_network:
        aliases:
          - db
    volumes:
      - psql_data:/var/lib/postgresql/data

  cache-redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      main_network:
        aliases:
          - cache


volumes:
  redis_data:
  psql_data:


networks:
  main_network:
